CREATE TABLE posts (
    path VARCHAR PRIMARY KEY,
    title VARCHAR NOT NULL,
    version VARCHAR NOT NULL,
    published BOOLEAN NOT NULL DEFAULT 'f',
    created TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated TIMESTAMP WITHOUT TIME ZONE
)
